// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../pgp.dart';
import '../circles.dart';
import 'circle.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_bytes`, `as_read`, `resign`, `tag_reader`, `to_read`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CircleAppInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleApp>>
abstract class CircleApp implements RustOpaqueInterface {
  Future<void> addApp({required CircleApp app, required MemberTag tag});

  Future<void> addCircle({required Circle circle, required MemberTag tag});

  Future<void> addUser({required UserHandle user, required MemberTag tag});

  Future<bool> isMember({required UserHandle user});

  Stream<AppMember> iterMembers();

  Future<void> merge({required CircleApp other});

  Future<void> mergeBoth({required CircleApp other});
}

class AppMember {
  final CircleOr? member;
  final MemberTag tag;

  const AppMember({this.member, required this.tag});

  @override
  int get hashCode => member.hashCode ^ tag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppMember &&
          runtimeType == other.runtimeType &&
          member == other.member &&
          tag == other.tag;
}

enum MemberTag { merge, overwrite, delete }
