// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../api.dart';
import '../../../frb_generated.dart';
import '../../db/connection.dart';
import '../../pgp.dart';
import '../circles.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bytes_buf`, `members_reader`, `new_mut`, `update_digest`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CircleInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Circle>>
abstract class Circle implements RustOpaqueInterface, CircleLike {
  Future<NonOpaqueCircle> consumeMembers();

  @override
  Uint8List getId();

  @override
  UserHandle getIdUserhandle();

  @override
  CircleEntry? getMember({required UserHandle id});

  @override
  CircleType getType();

  @override
  Future<void> insert({required SqliteDb db});

  Future<bool> isMember({required UserHandle user});

  @override
  Stream<CircleEntry> iterMembers();

  Future<void> setPgp({required PgpApp pgp});

  Future<void> toDb({required SqliteDb db});

  @override
  Future<bool> verify();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleAuthor>>
abstract class CircleAuthor implements RustOpaqueInterface {
  UserHandle get author;

  Uint8List get sig;

  set author(UserHandle author);

  set sig(Uint8List sig);
}

class NonOpaqueCircle {
  final UserHandle id;
  final List<CircleEntry> members;
  final UserHandle? author;
  final Uint8List? sig;

  const NonOpaqueCircle({
    required this.id,
    required this.members,
    this.author,
    this.sig,
  });

  Future<void> toDb({required SqliteDb db}) => RustLib.instance.api
      .crateApiPgpCirclesCircleNonOpaqueCircleToDb(that: this, db: db);

  @override
  int get hashCode =>
      id.hashCode ^ members.hashCode ^ author.hashCode ^ sig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NonOpaqueCircle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          members == other.members &&
          author == other.author &&
          sig == other.sig;
}
