// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'entities.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'store.dart';

// These functions are ignored because they are not marked as `pub`: `connection`, `fire_watchers`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SqliteDbInner`, `WatcherInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SqliteDb>>
abstract class SqliteDb implements RustOpaqueInterface, CertDao, Dao, TestDao {
  @override
  Future<List<PgpDataCert>> allCerts();

  @override
  Future<List<PgpDataCert>> allOwnedCerts();

  Future<bool> checkOnline({required String fingerprint});

  @override
  Future<void> clearRole({required String role});

  @override
  Future<void> deleteByFingerprint({required String fingerprint});

  @override
  Future<List<PgpDataCert>> getByDomain({required String domain});

  @override
  Future<List<PgpDataCert>> getByEmail({required String email});

  @override
  Future<PgpDataCert> getByFingerprint({required String fingerprint});

  @override
  Future<List<PgpDataCert>> getById({required String keyId});

  @override
  Future<List<PgpDataCert>> getByUserid({required String userid});

  @override
  Future<void> getConnection();

  @override
  Future<OnlyFingerprint?> getFingerprintForRole({required String role});

  Watcher getWatcher();

  @override
  Future<List<PgpDataCert>> grepByEmail({required String email});

  @override
  Future<List<PgpDataCert>> grepByEmailAnchorEnd({required String email});

  @override
  Future<List<PgpDataCert>> grepByEmailAnchorStart({required String email});

  @override
  Future<List<PgpDataCert>> grepByUserid({required String userid});

  @override
  Future<List<PgpDataCert>> grepByUseridAnchorEnd({required String userid});

  @override
  Future<List<PgpDataCert>> grepByUseridAnchorStart({required String userid});

  Future<void> insertGroup({required NewsGroup group});

  @override
  Future<OnlyOnline?> isOnline({required String fingerprint});

  factory SqliteDb({required String path}) =>
      RustLib.instance.api.crateApiDbConnectionSqliteDbNew(path: path);

  static SqliteDb newInMemory() =>
      RustLib.instance.api.crateApiDbConnectionSqliteDbNewInMemory();

  @override
  Future<List<PgpDataCert>> searchOwnedCerts({required String userid});

  @override
  Future<List<NewsGroup>> test({required UuidValue uuid});

  @override
  Future<NewsGroup?> testNullable();

  @override
  Future<NewsGroup> testOne();

  @override
  Future<void> updateRole({required String fingerprint, required String role});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Watcher>>
abstract class Watcher implements RustOpaqueInterface {
  void watch({
    required String table,
    required FutureOr<void> Function(SqliteDb) cb,
  });
}

abstract class Crud {
  Future<void> delete({required SqliteDb conn});

  Future<void> insert({required SqliteDb conn});

  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  });

  Future<void> update({required SqliteDb conn});
}

abstract class Dao {
  Future<void> getConnection();
}

enum OnConflict { update, ignore, abort }
