// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'connection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_row`, `from_row`, `from_row`, `from_rows`, `from_rows`, `from_rows`, `from_rows`, `from_rows`, `from_rows`, `from_rows`, `get_params`, `get_params`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `from_row`, `is_entity`, `is_entity`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NewsGroup>>
abstract class NewsGroup
    implements RustOpaqueInterface, Crud, FromRow, GetParams {
  String get description;

  String get groupName;

  UuidValue? get parent;

  Uint8List? get parentHash;

  bool get sent;

  UuidValue get uuid;

  set description(String description);

  set groupName(String groupName);

  set parent(UuidValue? parent);

  set parentHash(Uint8List? parentHash);

  set sent(bool sent);

  set uuid(UuidValue uuid);

  @override
  Future<void> delete({required SqliteDb conn});

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbEntitiesNewsGroupHasParams();

  @override
  Future<void> insert({required SqliteDb conn});

  @override
  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  });

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbEntitiesNewsGroupIsEntity();

  @override
  Future<void> update({required SqliteDb conn});
}

abstract class FromRow {}

abstract class GetParams {}

abstract class TestDao {
  Future<List<NewsGroup>> test({required UuidValue uuid});

  Future<NewsGroup?> testNullable();

  Future<NewsGroup> testOne();
}
