// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../pgp.dart';
import '../pgp/circles/app.dart';
import 'connection.dart';
import 'entities.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_tsk`, `get_bytes`, `get_userhandle`, `merge`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DbMembers`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_row`, `from_row`, `from_row`, `from_row`, `from_row`, `from_row`, `get_params`, `get_params`, `get_params`, `get_params`, `get_params`, `get_params`, `insert_on_conflict_custom`, `insert_on_conflict_custom`, `insert_on_conflict_custom`, `insert_on_conflict_custom`, `insert_on_conflict_custom`, `insert_on_conflict_custom`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `from_row`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleData>>
abstract class CircleData
    implements RustOpaqueInterface, Crud, FromRow, GetParams {
  @override
  Future<void> delete({required SqliteDb conn});

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStoreCircleDataHasParams();

  @override
  Future<void> insert({required SqliteDb conn});

  @override
  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  });

  @override
  Future<void> insertOnConflictCols({
    required SqliteDb conn,
    required OnConflict onConflict,
    required List<String> cols,
  });

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStoreCircleDataIsEntity();

  @override
  Future<void> update({required SqliteDb conn});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleMembersData>>
abstract class CircleMembersData
    implements RustOpaqueInterface, Crud, FromRow, GetParams {
  @override
  Future<void> delete({required SqliteDb conn});

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStoreCircleMembersDataHasParams();

  @override
  Future<void> insert({required SqliteDb conn});

  @override
  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  });

  @override
  Future<void> insertOnConflictCols({
    required SqliteDb conn,
    required OnConflict onConflict,
    required List<String> cols,
  });

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStoreCircleMembersDataIsEntity();

  @override
  Future<void> update({required SqliteDb conn});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleWithMembers>>
abstract class CircleWithMembers
    implements RustOpaqueInterface, Crud, FromRow, GetParams {
  @override
  Future<void> delete({required SqliteDb conn});

  Future<UserHandle?> getAuthor();

  Future<Uint8List> getId();

  Future<(String, Uint8List)> getIdTuple();

  Future<UserHandle> getIdUserhandle();

  Future<Uint8List?> getMemberId();

  Future<Uint8List?> getParentId();

  Future<(String, Uint8List)?> getParentTuple();

  Future<MemberTag?> getTag();

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStoreCircleWithMembersHasParams();

  @override
  Future<void> insert({required SqliteDb conn});

  @override
  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  });

  @override
  Future<void> insertOnConflictCols({
    required SqliteDb conn,
    required OnConflict onConflict,
    required List<String> cols,
  });

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStoreCircleWithMembersIsEntity();

  @override
  Future<void> update({required SqliteDb conn});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PgpDataCert>>
abstract class PgpDataCert
    implements RustOpaqueInterface, Crud, FromRow, GetParams {
  @override
  Future<void> delete({required SqliteDb conn});

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStorePgpDataCertHasParams();

  @override
  Future<void> insert({required SqliteDb conn});

  @override
  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  });

  @override
  Future<void> insertOnConflictCols({
    required SqliteDb conn,
    required OnConflict onConflict,
    required List<String> cols,
  });

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStorePgpDataCertIsEntity();

  @override
  Future<void> update({required SqliteDb conn});
}

abstract class CertDao {
  Future<List<PgpDataCert>> allCerts();

  Future<List<PgpDataCert>> allOwnedCerts();

  Future<void> clearRole({required String role});

  Future<void> deleteByFingerprint({required String fingerprint});

  Future<void> deleteCircle({required String id, required String ty});

  Future<void> deleteCircleMember({required String id});

  Future<List<PgpDataCert>> getByDomain({required String domain});

  Future<List<PgpDataCert>> getByEmail({required String email});

  Future<PgpDataCert> getByFingerprint({required String fingerprint});

  Future<List<PgpDataCert>> getById({required String keyId});

  Future<List<PgpDataCert>> getByUserid({required String userid});

  Future<List<CircleWithMembers>> getCircleById({
    required String id,
    required String ty,
  });

  Future<List<CircleWithMembers>> getCircleRoots();

  Future<List<CircleWithMembers>> getCirclesJoin();

  Future<List<CircleWithMembers>> getCirclesWithoutParent();

  Future<OnlyFingerprint?> getFingerprintForRole({required String role});

  Future<BigInt> getMigrationVersion();

  Future<List<PgpDataCert>> grepByEmail({required String email});

  Future<List<PgpDataCert>> grepByEmailAnchorEnd({required String email});

  Future<List<PgpDataCert>> grepByEmailAnchorStart({required String email});

  Future<List<PgpDataCert>> grepByUserid({required String userid});

  Future<List<PgpDataCert>> grepByUseridAnchorEnd({required String userid});

  Future<List<PgpDataCert>> grepByUseridAnchorStart({required String userid});

  Future<OnlyOnline?> isOnline({required String fingerprint});

  Future<List<PgpDataCert>> searchOwnedCerts({required String userid});

  Future<void> updateRole({required String fingerprint, required String role});

  Future<void> updateTag({required String tag, required String member});
}

class OnlyFingerprint {
  final String fingerprint;

  const OnlyFingerprint({required this.fingerprint});

  Future<void> delete({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyFingerprintDelete(that: this, conn: conn);

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStoreOnlyFingerprintHasParams();

  Future<void> insert({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyFingerprintInsert(that: this, conn: conn);

  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  }) => RustLib.instance.api.crateApiDbStoreOnlyFingerprintInsertOnConflict(
    that: this,
    conn: conn,
    onConflict: onConflict,
  );

  Future<void> insertOnConflictCols({
    required SqliteDb conn,
    required OnConflict onConflict,
    required List<String> cols,
  }) => RustLib.instance.api.crateApiDbStoreOnlyFingerprintInsertOnConflictCols(
    that: this,
    conn: conn,
    onConflict: onConflict,
    cols: cols,
  );

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStoreOnlyFingerprintIsEntity();

  Future<void> update({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyFingerprintUpdate(that: this, conn: conn);

  @override
  int get hashCode => fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnlyFingerprint &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint;
}

class OnlyOnline {
  final bool online;

  const OnlyOnline({required this.online});

  Future<void> delete({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyOnlineDelete(that: this, conn: conn);

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStoreOnlyOnlineHasParams();

  Future<void> insert({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyOnlineInsert(that: this, conn: conn);

  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  }) => RustLib.instance.api.crateApiDbStoreOnlyOnlineInsertOnConflict(
    that: this,
    conn: conn,
    onConflict: onConflict,
  );

  Future<void> insertOnConflictCols({
    required SqliteDb conn,
    required OnConflict onConflict,
    required List<String> cols,
  }) => RustLib.instance.api.crateApiDbStoreOnlyOnlineInsertOnConflictCols(
    that: this,
    conn: conn,
    onConflict: onConflict,
    cols: cols,
  );

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStoreOnlyOnlineIsEntity();

  Future<void> update({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyOnlineUpdate(that: this, conn: conn);

  @override
  int get hashCode => online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnlyOnline &&
          runtimeType == other.runtimeType &&
          online == other.online;
}
