// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'connection.dart';
import 'entities.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_tsk`, `merge`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `partial_cmp`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_row`, `from_row`, `from_row`, `get_params`, `get_params`, `get_params`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PgpDataCert>>
abstract class PgpDataCert
    implements RustOpaqueInterface, Crud, FromRow, GetParams {
  @override
  Future<void> delete({required SqliteDb conn});

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStorePgpDataCertHasParams();

  @override
  Future<void> insert({required SqliteDb conn});

  @override
  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  });

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStorePgpDataCertIsEntity();

  @override
  Future<void> update({required SqliteDb conn});
}

abstract class CertDao {
  Future<List<PgpDataCert>> allCerts();

  Future<List<PgpDataCert>> allOwnedCerts();

  Future<void> clearRole({required String role});

  Future<void> deleteByFingerprint({required String fingerprint});

  Future<List<PgpDataCert>> getByDomain({required String domain});

  Future<List<PgpDataCert>> getByEmail({required String email});

  Future<PgpDataCert> getByFingerprint({required String fingerprint});

  Future<List<PgpDataCert>> getById({required String keyId});

  Future<List<PgpDataCert>> getByUserid({required String userid});

  Future<OnlyFingerprint?> getFingerprintForRole({required String role});

  Future<List<PgpDataCert>> grepByEmail({required String email});

  Future<List<PgpDataCert>> grepByEmailAnchorEnd({required String email});

  Future<List<PgpDataCert>> grepByEmailAnchorStart({required String email});

  Future<List<PgpDataCert>> grepByUserid({required String userid});

  Future<List<PgpDataCert>> grepByUseridAnchorEnd({required String userid});

  Future<List<PgpDataCert>> grepByUseridAnchorStart({required String userid});

  Future<OnlyOnline?> isOnline({required String fingerprint});

  Future<List<PgpDataCert>> searchOwnedCerts({required String userid});

  Future<void> updateRole({required String fingerprint, required String role});
}

class OnlyFingerprint {
  final String fingerprint;

  const OnlyFingerprint({required this.fingerprint});

  Future<void> delete({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyFingerprintDelete(that: this, conn: conn);

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStoreOnlyFingerprintHasParams();

  Future<void> insert({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyFingerprintInsert(that: this, conn: conn);

  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  }) => RustLib.instance.api.crateApiDbStoreOnlyFingerprintInsertOnConflict(
    that: this,
    conn: conn,
    onConflict: onConflict,
  );

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStoreOnlyFingerprintIsEntity();

  Future<void> update({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyFingerprintUpdate(that: this, conn: conn);

  @override
  int get hashCode => fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnlyFingerprint &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint;
}

class OnlyOnline {
  final bool online;

  const OnlyOnline({required this.online});

  Future<void> delete({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyOnlineDelete(that: this, conn: conn);

  static Future<bool> hasParams() =>
      RustLib.instance.api.crateApiDbStoreOnlyOnlineHasParams();

  Future<void> insert({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyOnlineInsert(that: this, conn: conn);

  Future<void> insertOnConflict({
    required SqliteDb conn,
    required OnConflict onConflict,
  }) => RustLib.instance.api.crateApiDbStoreOnlyOnlineInsertOnConflict(
    that: this,
    conn: conn,
    onConflict: onConflict,
  );

  static Future<bool> isEntity() =>
      RustLib.instance.api.crateApiDbStoreOnlyOnlineIsEntity();

  Future<void> update({required SqliteDb conn}) => RustLib.instance.api
      .crateApiDbStoreOnlyOnlineUpdate(that: this, conn: conn);

  @override
  int get hashCode => online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnlyOnline &&
          runtimeType == other.runtimeType &&
          online == other.online;
}
