// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../api.dart';
import '../../frb_generated.dart';
import '../pgp.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'cert.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_bytes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PgpCert>>
abstract class PgpCert implements RustOpaqueInterface {
  UserHandle get fingerprint;

  bool get hasPrivate;

  String get keyid;

  bool get online;

  set fingerprint(UserHandle fingerprint);

  set hasPrivate(bool hasPrivate);

  set keyid(String keyid);

  set online(bool online);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PgpCertStubSigs>>
abstract class PgpCertStubSigs implements RustOpaqueInterface {
  PgpCert get cert;

  List<String> get certifications;

  List<String> get ids;

  List<String> get sigs;

  set cert(PgpCert cert);

  set certifications(List<String> certifications);

  set ids(List<String> ids);

  set sigs(List<String> sigs);

  static PgpCertStubSigs fromBytes({required List<int> bytes}) => RustLib
      .instance
      .api
      .crateApiPgpCertPgpCertStubSigsFromBytes(bytes: bytes);

  static Future<PgpCertStubSigs> fromBytesSig({
    required List<int> bytes,
    required PgpApp store,
  }) => RustLib.instance.api.crateApiPgpCertPgpCertStubSigsFromBytesSig(
    bytes: bytes,
    store: store,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PgpCertWithIds>>
abstract class PgpCertWithIds implements RustOpaqueInterface {
  PgpCert get cert;

  List<MaybeCert> get certifications;

  List<String> get ids;

  List<MaybeCert> get sigs;

  set cert(PgpCert cert);

  set certifications(List<MaybeCert> certifications);

  set ids(List<String> ids);

  set sigs(List<MaybeCert> sigs);

  PgpCertWithIds copy();

  static PgpCertWithIds fromBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiPgpCertPgpCertWithIdsFromBytes(bytes: bytes);

  static Future<PgpCertWithIds> fromBytesSig({
    required List<int> bytes,
    required PgpApp store,
  }) => RustLib.instance.api.crateApiPgpCertPgpCertWithIdsFromBytesSig(
    bytes: bytes,
    store: store,
  );

  bool hasPrivate();

  String idHex();
}

@freezed
sealed class MaybeCert with _$MaybeCert {
  const MaybeCert._();

  const factory MaybeCert.full({required PgpCertWithIds cert}) = MaybeCert_Full;
  const factory MaybeCert.fingerprint({required UserHandle fpr}) =
      MaybeCert_Fingerprint;

  UserHandle fingerprint() =>
      RustLib.instance.api.crateApiPgpCertMaybeCertFingerprint(that: this);

  static MaybeCert fromCert({required PgpCertWithIds cert}) =>
      RustLib.instance.api.crateApiPgpCertMaybeCertFromCert(cert: cert);

  List<String>? maybeIds() =>
      RustLib.instance.api.crateApiPgpCertMaybeCertMaybeIds(that: this);
}
