// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../db/connection.dart';
import '../db/store.dart';
import '../pgp.dart';
import 'circles/app.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_bytes`, `from_app_member`, `from_circle_or`, `get_children_parent`, `get_children`, `get_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TagOr`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `partial_cmp`, `partial_cmp`, `partial_cmp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleEntry>>
abstract class CircleEntry implements RustOpaqueInterface {
  CircleOr? get content;

  UserHandle get id;

  MemberTag? get tag;

  set content(CircleOr? content);

  set id(UserHandle id);

  set tag(MemberTag? tag);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleOr>>
abstract class CircleOr implements RustOpaqueInterface {
  static Future<List<CircleOr>> fromDb({
    required List<CircleWithMembers> members,
  }) => RustLib.instance.api.crateApiPgpCirclesCircleOrFromDb(members: members);

  Future<String> idHex();

  Future<bool> isMember({required UserHandle user});

  Future<void> toDb({required SqliteDb db});
}

abstract class CircleLike {
  Future<List<CircleEntry>> consumeMembers();

  Future<Uint8List> getId();

  Future<UserHandle> getIdUserhandle();

  Future<CircleEntry?> getMember({required UserHandle id});

  Stream<CircleEntry> iterMembers();

  Future<bool> verify();
}
