// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../api.dart';
import '../../frb_generated.dart';
import '../db/connection.dart';
import '../pgp.dart';
import 'circles/app.dart';
import 'circles/circle.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'circles.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `as_bytes`, `as_read`, `as_read`, `empty`, `from_circle_or_tag`, `from_circle_or`, `get_bin`, `get_bytes`, `get_children_parent`, `get_children`, `get_parent_cache`, `get_type_str`, `get_type_u8`, `get_userhandle`, `into_option`, `is_none`, `member_type`, `option_mut`, `option`, `thin`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CircleOrRef`, `MaybeDeletedFull`, `TagOr`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `cmp`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`, `hash`, `hash`, `hash`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `read`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `get_id_userhandle`, `get_id`, `get_member`, `get_members`, `get_name`, `get_owner`, `get_type`, `handle`, `insert`, `iter_members`, `validate`, `verify`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleEntry>>
abstract class CircleEntry implements RustOpaqueInterface {
  CircleOr? get content;

  CircleHandle get id;

  MemberTag? get tag;

  set content(CircleOr? content);

  set id(CircleHandle id);

  set tag(MemberTag? tag);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CircleHandle>>
abstract class CircleHandle implements RustOpaqueInterface {
  CircleType get circleType;

  UserHandle get id;

  set circleType(CircleType circleType);

  set id(UserHandle id);
}

abstract class CircleLike {
  Uint8List getId();

  UserHandle getIdUserhandle();

  CircleEntry? getMember({required CircleHandle id});

  List<CircleEntry> getMembers();

  String getName();

  UserHandle? getOwner();

  CircleType getType();

  CircleHandle handle();

  Future<void> insert({required SqliteDb db});

  Stream<CircleEntry> iterMembers();

  Future<bool> validate();

  Future<bool> verify();
}

@freezed
sealed class CircleOr with _$CircleOr {
  const CircleOr._();

  const factory CircleOr.circle(Circle field0) = CircleOr_Circle;
  const factory CircleOr.user(UserHandle field0) = CircleOr_User;
  const factory CircleOr.app(CircleApp field0) = CircleOr_App;

  Future<void> add({
    required CircleOr circle,
    required MemberTag tag,
    required PgpApp db,
  }) => RustLib.instance.api.crateApiPgpCirclesCircleOrAdd(
    that: this,
    circle: circle,
    tag: tag,
    db: db,
  );

  static CircleOr fromCert({required UserHandle userHandle}) => RustLib
      .instance
      .api
      .crateApiPgpCirclesCircleOrFromCert(userHandle: userHandle);

  Uint8List getId() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrGetId(that: this);

  UserHandle getIdUserhandle() => RustLib.instance.api
      .crateApiPgpCirclesCircleOrGetIdUserhandle(that: this);

  CircleEntry? getMember({required CircleHandle id}) => RustLib.instance.api
      .crateApiPgpCirclesCircleOrGetMember(that: this, id: id);

  List<CircleEntry> getMembers() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrGetMembers(that: this);

  String getName() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrGetName(that: this);

  UserHandle? getOwner() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrGetOwner(that: this);

  CircleType getType() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrGetType(that: this);

  CircleHandle handle() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrHandle(that: this);

  String idHex() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrIdHex(that: this);

  Future<void> insert({required SqliteDb db}) =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrInsert(that: this, db: db);

  Future<bool> isMember({required CircleHandle user}) => RustLib.instance.api
      .crateApiPgpCirclesCircleOrIsMember(that: this, user: user);

  Stream<CircleEntry> iterMembers() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrIterMembers(that: this);

  Future<void> toDb({required SqliteDb db}) =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrToDb(that: this, db: db);

  Future<bool> validate() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrValidate(that: this);

  Future<bool> verify() =>
      RustLib.instance.api.crateApiPgpCirclesCircleOrVerify(that: this);
}

enum CircleType {
  user,
  circle,
  app;

  static Future<CircleType> fromStr({required String s}) =>
      RustLib.instance.api.crateApiPgpCirclesCircleTypeFromStr(s: s);
}
