// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../pgp.dart';
import 'circles/app.dart';
import 'circles/circle.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'circles.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `as_bytes`, `get_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `cmp`, `eq`, `fmt`, `partial_cmp`

@freezed
sealed class CircleOr with _$CircleOr {
  const CircleOr._();

  const factory CircleOr.circle(Circle field0) = CircleOr_Circle;
  const factory CircleOr.user(UserHandle field0) = CircleOr_User;
  const factory CircleOr.app(CircleApp field0) = CircleOr_App;

  Future<bool> isMember({required UserHandle user}) => RustLib.instance.api
      .crateApiPgpCirclesCircleOrIsMember(that: this, user: user);
}
