// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bytes_to_n_fair`, `data_to_emoji`, `data_to_gismu_2`, `data_to_gismu`, `data_to_phone`, `get_gismu`, `lujvo_combined`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GISMU`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

class VisualKey {
  final List<String> gismu;
  final List<String> emoji;
  final String phone;

  const VisualKey({
    required this.gismu,
    required this.emoji,
    required this.phone,
  });

  @override
  int get hashCode => gismu.hashCode ^ emoji.hashCode ^ phone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisualKey &&
          runtimeType == other.runtimeType &&
          gismu == other.gismu &&
          emoji == other.emoji &&
          phone == other.phone;
}
