// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_reader`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PgpImportReader`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `read_exact`, `read`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Lifetimeable < Result < CertParser < 'static > > >>>
abstract class ResultCertParser implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PgpImportBytes>>
abstract class PgpImportBytes implements RustOpaqueInterface, PgpImport {
  Future<void> accept({required List<int> bytes});

  @override
  Future<ResultCertParser> getPackets();

  factory PgpImportBytes() =>
      RustLib.instance.api.crateApiPgpImportPgpImportBytesNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PgpImportFile>>
abstract class PgpImportFile implements RustOpaqueInterface, PgpImport {
  @override
  Future<ResultCertParser> getPackets();

  factory PgpImportFile({required String path}) =>
      RustLib.instance.api.crateApiPgpImportPgpImportFileNew(path: path);
}

abstract class PgpImport {
  Future<ResultCertParser> getPackets();
}
