// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'cert.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_api_cert`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GenerateCertInner`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `get_key_from_fingerprint`, `iter_certs_search_keyid`, `iter_certs_search`, `iter_certs`, `iter_fingerprints`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GenerateCert>>
abstract class GenerateCert implements RustOpaqueInterface {
  GenerateCert comment({required String comment});

  Future<PgpCertWithIds> generate();

  GenerateCert name({required String name});

  GenerateCert online({required bool online});
}
