// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sign.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_app`, `get_trust`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PgpAppVerifier`, `SignMerge`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `check`, `check`, `get_certs`, `get_certs`, `merge_public`

@freezed
sealed class TrustLevel with _$TrustLevel {
  const TrustLevel._();

  const factory TrustLevel.ultimate() = TrustLevel_Ultimate;
  const factory TrustLevel.full() = TrustLevel_Full;
  const factory TrustLevel.partial() = TrustLevel_Partial;
  const factory TrustLevel.custom(int field0) = TrustLevel_Custom;
}
