// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../pgp.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'visual_key.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `apply`, `bytes_to_n_fair`, `data_to_emoji`, `data_to_gismu_2`, `data_to_gismu`, `data_to_phone`, `get_gismu`, `identicon`, `is_overlapping`, `lujvo_combined`, `validate_overlap_single`, `validate_overlap`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GISMU`, `IdenticonConfig`, `VisualKeyBuilderInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `deref`, `fmt`, `fmt`, `fmt`, `initialize`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Lifetimeable < VisualKeyBuilder < 'static > >>>
abstract class VisualKeyBuilder implements RustOpaqueInterface {
  Future<VisualKeyOr> applyOrElse();

  VisualKeyBuilder emoji({required BigInt start, required BigInt end});

  static VisualKeyBuilder fromHandle({required UserHandle data}) => RustLib
      .instance
      .api
      .crateApiPgpFingerprintVisualKeyLifetimeableAutoOwnedRustOpaqueFlutterRustBridgeforGeneratedRustAutoOpaqueInnerVisualKeyBuilderstaticFromHandle(
        data: data,
      );

  Future<SizedImage?> getIdenticon();

  VisualKeyBuilder identicon({
    required BigInt start,
    required BigInt end,
    required int count,
    required int scale,
  });

  VisualKeyBuilder lujvo({required BigInt start, required BigInt end});

  VisualKeyBuilder phone({required BigInt start, required BigInt end});
}

class SizedImage {
  final Uint8List buf;
  final int height;
  final int width;

  const SizedImage({
    required this.buf,
    required this.height,
    required this.width,
  });

  @override
  int get hashCode => buf.hashCode ^ height.hashCode ^ width.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SizedImage &&
          runtimeType == other.runtimeType &&
          buf == other.buf &&
          height == other.height &&
          width == other.width;
}

class VisualKey {
  final List<String>? gismu;
  final List<String>? emoji;
  final String? phone;

  const VisualKey({this.gismu, this.emoji, this.phone});

  String joinEmoji() => RustLib.instance.api
      .crateApiPgpFingerprintVisualKeyVisualKeyJoinEmoji(that: this);

  String joinGismu() => RustLib.instance.api
      .crateApiPgpFingerprintVisualKeyVisualKeyJoinGismu(that: this);

  @override
  int get hashCode => gismu.hashCode ^ emoji.hashCode ^ phone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisualKey &&
          runtimeType == other.runtimeType &&
          gismu == other.gismu &&
          emoji == other.emoji &&
          phone == other.phone;
}

@freezed
sealed class VisualKeyOr with _$VisualKeyOr {
  const VisualKeyOr._();

  const factory VisualKeyOr.gismu(VisualKey field0) = VisualKeyOr_Gismu;
  const factory VisualKeyOr.name(String field0) = VisualKeyOr_Name;
}
