// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pgp/cert.dart';
import 'pgp/import.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PgpServiceStore`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `import_certs`, `new`

abstract class PgpServiceTrait {
  Future<String> exportArmor();

  Future<void> exportFile({required String file});

  Future<PgpCertWithIds> getKeyFromFingerprint({required String fingerprint});

  Future<void> importCerts({required PgpImport import_});

  Stream<PgpCertWithIds> iterCerts();

  Stream<PgpCertWithIds> iterCertsSearch({required String pattern});

  Stream<PgpCertWithIds> iterCertsSearchKeyid({required String pattern});

  Stream<String> iterFingerprints();
}

abstract class Verifier {
  Future<bool> verify({required List<int> data});
}
