// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pgp/cert.dart';

// These functions are ignored because they are not marked as `pub`: `strip_cert`

class QrCodeContent {
  final String resource;
  final String? handle;
  final String? description;

  const QrCodeContent({required this.resource, this.handle, this.description});

  @override
  int get hashCode =>
      resource.hashCode ^ handle.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrCodeContent &&
          runtimeType == other.runtimeType &&
          resource == other.resource &&
          handle == other.handle &&
          description == other.description;
}

class QrCodeKey {
  final Uint8List content;
  final Uint8List? fullkey;

  const QrCodeKey({required this.content, this.fullkey});

  @override
  int get hashCode => content.hashCode ^ fullkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrCodeKey &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          fullkey == other.fullkey;
}

class VerifyResult {
  final List<String> fingerprints;
  final QrCodeContent? content;
  final PgpCertWithIds? key;
  final bool isStub;

  const VerifyResult({
    required this.fingerprints,
    this.content,
    this.key,
    required this.isStub,
  });

  @override
  int get hashCode =>
      fingerprints.hashCode ^ content.hashCode ^ key.hashCode ^ isStub.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyResult &&
          runtimeType == other.runtimeType &&
          fingerprints == other.fingerprints &&
          content == other.content &&
          key == other.key &&
          isStub == other.isStub;
}
