// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'path.dart';

// These functions are ignored because they are not marked as `pub`: `authenticate_internal`, `dump_internal`
// These functions are ignored because they have generic arguments: `from_store`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CertNetwork`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `from_store_unrooted`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SharedNetwork>>
abstract class SharedNetwork implements RustOpaqueInterface, CertNetworkTrait {
  @override
  Future<WotGraph> authenticate({
    required String remote,
    required BigInt trust,
  });

  @override
  Future<WotGraph> dumpAll();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StoreNetwork>>
abstract class StoreNetwork implements RustOpaqueInterface, CertNetworkTrait {
  @override
  Future<WotGraph> authenticate({
    required String remote,
    required BigInt trust,
  });

  @override
  Future<WotGraph> dumpAll();
}

abstract class CertNetworkTrait {
  Future<WotGraph> authenticate({
    required String remote,
    required BigInt trust,
  });

  Future<WotGraph> dumpAll();
}
