// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `eq`, `eq`, `hash`, `hash`

class GraphEdge {
  final String srcId;
  final String dstId;
  final PlatformInt64 ranking;
  final String edgeName;

  const GraphEdge({
    required this.srcId,
    required this.dstId,
    required this.ranking,
    required this.edgeName,
  });

  @override
  int get hashCode =>
      srcId.hashCode ^ dstId.hashCode ^ ranking.hashCode ^ edgeName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphEdge &&
          runtimeType == other.runtimeType &&
          srcId == other.srcId &&
          dstId == other.dstId &&
          ranking == other.ranking &&
          edgeName == other.edgeName;
}

class GraphVertex {
  final String id;
  final String tag;
  final List<String> tags;
  final Uint8List? data;

  const GraphVertex({
    required this.id,
    required this.tag,
    required this.tags,
    this.data,
  });

  @override
  int get hashCode =>
      id.hashCode ^ tag.hashCode ^ tags.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphVertex &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tag == other.tag &&
          tags == other.tags &&
          data == other.data;
}

class WotGraph {
  final Set<GraphEdge> edges;
  final Map<String, GraphVertex> vertices;
  final BigInt trust;

  const WotGraph({
    required this.edges,
    required this.vertices,
    required this.trust,
  });

  @override
  int get hashCode => edges.hashCode ^ vertices.hashCode ^ trust.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WotGraph &&
          runtimeType == other.runtimeType &&
          edges == other.edges &&
          vertices == other.vertices &&
          trust == other.trust;
}
